Create `/tmp/tools` on Jenkins agents with correct permissions `jenkins:jenkins`, to avoid `root:root`
We faced with an issue, when sometimes Jenkins agent can't download tools into `/tmp/tools` because of wrong owner `root:root`:

> hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.x.x.x/172.x.x.x:41124
> …
> java.nio.file.AccessDeniedException: /tmp/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation
> …
> Caused: java.io.IOException: Failed to install https://nodejs.org/dist/v12.5.0/node-v12.5.0-linux-x64.tar.gz to /tmp/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/serverlessv2-nodejs-oco

This error can be caused because of using containerizing stage in Jenkins pipeline, when pipeline steps can be executed as `root`.
Probably option `reuseNode true` forces Jenkins to mount `/tmp/` from the host system into container.